name: Sync to Repo2

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo1
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.name "lehonganh0201"
          git config --global user.email "lehonganh0201@users.noreply.github.com"

      - name: Clone Repo2
        run: |
          git clone https://x-access-token:${{ secrets.REPO2_TOKEN }}@github.com/lehonganh0201/DATN-LeHongAnh-2022DHKTPM01-FE.git DATN-LeHongAnh-2022DHKTPM01-FE

      - name: Copy files from Repo1 to Repo2
        run: |
          rsync -av \
            --exclude='.git' \
            --exclude='.github' \
            ./ DATN-LeHongAnh-2022DHKTPM01-FE/

      - name: Commit and push changes
        run: |
          cd DATN-LeHongAnh-2022DHKTPM01-FE
          COMMIT_MSG=$(git -C .. log -1 --pretty=%B)
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "$COMMIT_MSG"
            git push origin main
          fi
